-- objects_classes holds vehicle class information for the admin tool
create table if not exists objects_classes (
	Classname	varchar(128) not null default '',
	Type		varchar(128) default null,

	primary key (Classname)
) character set utf8 engine=InnoDB;

insert igone into objects_classes (Classname, Type) values
('ATV_CZ_EP1', 'ATV'),
('ATV_US_EP1', 'ATV'),
('BAF_Offroad_W', 'Car'),
('car_hatchback', 'Car'),
('car_sedan', 'Car'),
('datsun1_civil_3_open', 'Car'),
('Fishing_Boat', 'large Boat'),
('Hedgehog_DZ', 'Hedgehog'),
('hilux1_civil_1_open', 'Car'),
('hilux1_civil_2_covered', 'Car'),
('hilux1_civil_3_open', 'Car'),
('HMMWV', 'Car'),
('Ikarus', 'Bus'),
('Ikarus_TK_CIV_EP1', 'Bus'),
('Kamaz', 'Truck'),
('LandRover_TK_CIV_EP1', 'Car'),
('MH6J_EP1', 'Helicopter'),
('Old_bike_TK_CIV_EP1', 'Bike'),
('Old_bike_TK_INS_EP1', 'Bike'),
('PBX', 'small Boat'),
('S1203_TK_CIV_EP1', 'Bus'),
('Skoda', 'Car'),
('SkodaBlue', 'Car'),
('SkodaGreen', 'Car'),
('Smallboat_1', 'medium Boat'),
('Smallboat_2', 'medium Boat'),
('SUV_TK_CIV_EP1', 'Car'),
('TentStorage', 'Tent'),
('Tractor', 'Farmvehicle'),
('TT650_Ins', 'Motorcycle'),
('TT650_TK_CIV_EP1', 'Motorcycle'),
('TT650_TK_EP1', 'Motorcycle'),
('UAZ_INS', 'Car'),
('UAZ_RU', 'Car'),
('UAZ_Unarmed_TK_CIV_EP1', 'Car'),
('UAZ_Unarmed_TK_EP1', 'Car'),
('UAZ_Unarmed_UN_EP1', 'Car'),
('UH1H_DZ', 'Helicopter'),
('UralCivil', 'Truck'),
('UralCivil2', 'Truck'),
('V3S_Civ', 'Truck'),
('V3S_Gue', 'Truck'),
('V3S_TK_GUE_EP1', 'Truck'),
('VolhaLimo_TK_CIV_EP1', 'Car'),
('Volha_1_TK_CIV_EP1', 'Car'),
('Volha_2_TK_CIV_EP1', 'Car'),
('VWGolf', 'Car'),
('Wire_cat1', 'Wire');